name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: docker
    container:
      image: oven/bun:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build
        
      - name: Deploy to Cloudflare Workers
        timeout-minutes: 10
        run: |
            ls -la
            pwd
            bunx wrangler deploy --config wrangler.json 2>&1
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}